/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface TranslateRequest {
  /** @nullable */
  language?: string | null
  /** @nullable */
  systemPrompt?: string | null
  /** @nullable */
  temperature?: number | null
  /** @nullable */
  textBlockId?: string | null
}
